# syntax = docker/dockerfile:experimental
ARG SPRYKER_PLATFORM_IMAGE=spryker/php:7.3
FROM ${SPRYKER_PLATFORM_IMAGE} AS application-basic

ENV SPRYKER_IN_DOCKER=1
ENV COMPOSER_IGNORE_CHROMEDRIVER=1
{% for envName, envValue in _envs %}
ENV {{ envName }}='{{ envValue }}'
{% endfor %}

WORKDIR /data

# Create log directory
ARG SPRYKER_LOG_DIRECTORY
ENV SPRYKER_LOG_DIRECTORY=${SPRYKER_LOG_DIRECTORY}
RUN mkdir -p ${SPRYKER_LOG_DIRECTORY} && \
chown spryker:spryker ${SPRYKER_LOG_DIRECTORY}

# Creates the list of known hosts
ARG KNOWN_HOSTS
RUN mkdir -p /home/spryker/.ssh && chmod 0700 /home/spryker/.ssh
RUN bash -c '[ ! -z "${KNOWN_HOSTS}" ] && ssh-keyscan -t rsa ${KNOWN_HOSTS} >> /home/spryker/.ssh/known_hosts || true'
RUN chown spryker:spryker -R /home/spryker/.ssh

# PHP configuration
COPY php/php-fpm.d/worker.conf /usr/local/etc/php-fpm.d/worker.conf
COPY php/php.ini /usr/local/etc/php/
COPY php/conf.d/90-opcache.ini /usr/local/etc/php/conf.d
# removing default opcache.ini
RUN rm -f /usr/local/etc/php/conf.d/opcache.ini

{% if _phpExtensions is defined and _phpExtensions is not empty %}
{% for phpExtention in _phpExtensions %}
RUN mv /usr/local/etc/php/disabled/{{phpExtention}}.ini /usr/local/etc/php/conf.d/90-{{phpExtention}}.ini
{% endfor %}
{% endif %}

COPY php/conf.d/99-from-deploy-yaml-php.ini /usr/local/etc/php/conf.d/

# Jenkins
COPY --chown=spryker:spryker jenkins/jenkins.docker.xml.twig /home/spryker/jenkins.docker.xml.twig

# Build info
COPY --chown=spryker:spryker php/build.php /home/spryker/build.php

RUN --mount=type=cache,id=apk,sharing=locked,target=/var/cache/apk mkdir -p /etc/apk && ln -vsf /var/cache/apk /etc/apk/cache && \
bash -c 'if [ ! -z "$(which apk)" ]; then apk update && apk add \
bash \
mc \
curl \
util-linux \
libreoffice-common \
libreoffice-writer \
ttf-droid-nonlatin \
ttf-droid \
ttf-dejavu \
ttf-freefont \
ttf-liberation \
&& curl -Ls $UNO_URL -o /usr/local/bin/unoconv \
&& chmod +x /usr/local/bin/unoconv \
&& ln -s /usr/bin/python3 /usr/bin/python \
; fi'

RUN --mount=type=cache,id=aptlib,sharing=locked,target=/var/lib/apt \
--mount=type=cache,id=aptcache,sharing=locked,target=/var/cache/apt \
bash -c 'if [ ! -z "$(which apt)" ]; then apt-get update && apt-get install -y \
unoconv \
; fi'
